// <auto-generated />
using System;
using FunctionAppTest.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunctionAppTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250224174757_initialsetup")]
    partial class initialsetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FunctionAppTest.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Chandan",
                            CreatedOn = new DateTime(2025, 2, 24, 23, 17, 53, 777, DateTimeKind.Local).AddTicks(8427),
                            ModifiedBy = "Chandan",
                            ModifiedOn = new DateTime(2025, 2, 24, 23, 17, 53, 777, DateTimeKind.Local).AddTicks(8443),
                            ProductName = "DefaultP1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Amit",
                            CreatedOn = new DateTime(2025, 2, 24, 23, 17, 53, 777, DateTimeKind.Local).AddTicks(8480),
                            ModifiedBy = "Amit",
                            ModifiedOn = new DateTime(2025, 2, 24, 23, 17, 53, 777, DateTimeKind.Local).AddTicks(8481),
                            ProductName = "DefaultP2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
